server:
  port: 8001
spring:
  profiles: dev
  application:
    name: aaaa
---
server:
  port: 8201
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: cn.mldn.vo            # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev01
  application:
    name: roy200920092009
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://192.168.68.244:3306/mldn8001           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
eureka:
  client:
    service-url:
      #Eureka服务器的连接，默认为http：//XXXX：X/eureka/
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka,http://edmin:mldnjava@eureka-7002.com:7002/eureka,http://edmin:mldnjava@eureka-7003.com:7003/eureka
  instance: # eureak实例配置
    #此实例注册到eureka服务端的唯一标识,其组成为${spring.application.name}:${spring.application.instance_id:${random.value}}
    instance-id: microcloud-provider-dept-8201
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
    #lease-renewal-interval-in-seconds: 2     #设置心跳的时间间隔为2秒（默认是30秒）
    #lease-expiration-duration-in-seconds: 5  #如果现在超过了5秒间隔没发现这个服务，说明这个服务挂掉了（默认是90秒）
info:
  app.name: mldn-microcloud
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.verson$

---
server:
  port: 8202
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: cn.mldn.vo            # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev02
  application:
    name: roy200920092009
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://192.168.68.244:3306/mldn8001           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
eureka:
  client:
    service-url:
      #Eureka服务器的连接，默认为http：//XXXX：X/eureka/
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka,http://edmin:mldnjava@eureka-7002.com:7002/eureka,http://edmin:mldnjava@eureka-7003.com:7003/eureka
  instance: # eureak实例配置
    #此实例注册到eureka服务端的唯一标识,其组成为${spring.application.name}:${spring.application.instance_id:${random.value}}
    instance-id: microcloud-provider-dept-8201
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
    #lease-renewal-interval-in-seconds: 2     #设置心跳的时间间隔为2秒（默认是30秒）
    #lease-expiration-duration-in-seconds: 5  #如果现在超过了5秒间隔没发现这个服务，说明这个服务挂掉了（默认是90秒）
info:
  app.name: mldn-microcloud
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.verson$

