server:
  port: 8001
spring:
  profiles: dev
  application:
    name: aaaa
---
server:
  port: 8080
spring:
  profiles: default
  application:
    name: bbbb
---
server:
  port: 8081
spring:
  profiles: default
  application:
    name: dddd
---
server:
  port: 8888
spring:
  profiles: gan
  application:
    name: ccc