server:
  port: 7001
spring:
  profiles: erueka
    active: 
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microconfig-test-dev
---
server:
  port: 8080
spring:
  profiles: default
  application:
    name: microconfig-test-default