server:
  port: 7001
spring:
  profiles: erueka_7001
security:
  basic:
    enabled: true #启用安全认证
  user:
    name: edmin  #用户名
    password: mldnjava #密码  
eureka:
  server:
    #eviction-interval-timer-in-ms: 1000 #设置清理的时间间隔（单位毫秒，默认是60秒）
    enable-self-preservation: false # 设置为false表示关闭保护模式
  instance: # eureak实例配置
    hostname: eureka-7001.com # 定义Eureka实例所在的主机名称
    instance-id: 127.0.0.1:${server.port}
    prefer-ip-address: true # 以IP地址注册到服务中心，相互注册使用IP地址
  client:
    service-url:
      # Eureka服务器的连接，默认为http：//XXXX：X/eureka/
      defaultZone: http://edmin:mldnjava@eureka-7002.com:7002/eureka,http://edmin:mldnjava@eureka-7003.com:7003/eureka
    register-with-eureka: false
    fetch-registry: false

---

server:
  port: 7002
spring:
  profiles: erueka_7002
security:
  basic:
    enabled: true #启用安全认证
  user:
    name: edmin  #用户名
    password: mldnjava #密码  
eureka:
  server:
    #eviction-interval-timer-in-ms: 1000 #设置清理的时间间隔（单位毫秒，默认是60秒）
    enable-self-preservation: false # 设置为false表示关闭保护模式
  instance: # eureak实例配置
    hostname: eureka-7002.com # 定义Eureka实例所在的主机名称
    instance-id: 127.0.0.1:${server.port}
    prefer-ip-address: true # 以IP地址注册到服务中心，相互注册使用IP地址
  client:
    service-url:
      # Eureka服务器的连接，默认为http：//XXXX：X/eureka/
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka,http://edmin:mldnjava@eureka-7003.com:7003/eureka
    register-with-eureka: false
    fetch-registry: false

---

server:
  port: 7003
spring:
  profiles: erueka_7003
security:
  basic:
    enabled: true #启用安全认证
  user:
    name: edmin  #用户名
    password: mldnjava #密码  
eureka:
  server:
    #eviction-interval-timer-in-ms: 1000 #设置清理的时间间隔（单位毫秒，默认是60秒）
    enable-self-preservation: false # 设置为false表示关闭保护模式
  instance: # eureak实例配置
    hostname: eureka-7003.com # 定义Eureka实例所在的主机名称
    instance-id: 127.0.0.1:${server.port}
    prefer-ip-address: true # 以IP地址注册到服务中心，相互注册使用IP地址
  client:
    service-url:
      # Eureka服务器的连接，默认为http：//XXXX：X/eureka/
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka,http://edmin:mldnjava@eureka-7002.com:7002/eureka
    register-with-eureka: false
    fetch-registry: false