spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application: 
    name: microcloud-config-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://192.168.68.244:3306/mldn8001           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间 
eureka: 
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka,http://edmin:mldnjava@eureka-7002.com:7002/eureka,http://edmin:mldnjava@eureka-7003.com:7003/eureka
  instance: # eureak实例配置
    #此实例注册到eureka服务端的唯一标识,其组成为${spring.application.name}:${spring.application.instance_id:${random.value}}
    instance-id: 8201_local
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
info:
  app.name: mldn-microcloud
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.verson$
---
server:
  port: 8102
spring:
  profiles: beta
  application: 
    name: microcloud-config-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://192.168.68.244:3306/mldn8001           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间 
eureka: 
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka,http://edmin:mldnjava@eureka-7002.com:7002/eureka,http://edmin:mldnjava@eureka-7003.com:7003/eureka
  instance: # eureak实例配置
    #此实例注册到eureka服务端的唯一标识,其组成为${spring.application.name}:${spring.application.instance_id:${random.value}}
    instance-id: 8102_local
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
info:
  app.name: mldn-microcloud
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.verson$