spring:
  cloud:
    config:
      name: microcloud-config-client    # 定义要读取的资源文件的名称
      profile: beta      # 定义profile的 名称
      label: master     # 定义配置文件所在的分支
      uri: http://config-7101.com:7101  # SpringCloudConfig的服务地址
      username: mldnjava  # 连接的用户名
      password: hello   # 连接的密码